services:
  mariadb:
    image: mariadb:1.0

    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    secrets:
      - db_password
      - db_root_password

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception


  wordpress:
    image: wordpress:1.0

    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception

    depends_on:
      - mariadb


  nginx:
    image: nginx:1.0

    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always

    ports:
      - "443:443"

    volumes:
      - wordpress_data:/var/www/html:ro

    networks:
      - inception

    depends_on:
      - wordpress


secrets:
  db_password:
    file: ../secrets/db_password.txt

  db_root_password:
    file: ../secrets/db_root_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/remy/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/remy/data/wordpress


networks:
  inception:
    driver: bridge